replicaCount: 1
image:
  repo: crccheck/hello-world
  tag: "latest"
imagePullPolicy: IfNotPresent
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
